---
title: "ADS Project 2"
author: "Minzhi Zhang mz2787"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
# library(dplyr)
# library(readr)
# df <- list.files(path="/Users/mz/Desktop/Applied Data Science/ADS-group-3/output/csse_covid_19_daily_reports_us", full.names = TRUE) %>% 
#   lapply(read_csv) %>%
#   bind_rows 
# 
# tail(df)
```

```{r, message=FALSE}
library(dplyr)
library(readr)
file_name <- list.files(path="/Users/mz/Desktop/Applied Data Science/ADS-group-3/output/csse_covid_19_daily_reports_us", full.names = TRUE)
data <- data.frame()
date <- c()
for (file in file_name) {
  if (grepl('.csv$', file)) {
    date <- regmatches(file, regexpr("[0-9]{2}-[0-9]{2}-[0-9]{4}", file))
    full_data <- read_csv(file) %>%
              mutate(date = date)
    data <- data %>%
              bind_rows(full_data)
  }
}

data$date <- as.Date(data$date, "%m-%d-%Y")
head(data)
tail(data)

write.csv(data,'/Users/mz/Desktop/Applied Data Science/ADS-group-3/output/covid_data_2.csv')
```


```{r, message=FALSE}
merge_1 <- read_csv("/Users/mz/Desktop/Applied Data Science/ADS-group-3/output/merge_1.csv")
# merge_data <- read_csv("/Users/mz/Desktop/Applied Data Science/ADS-group-3/output/merge_data.csv")

# tail(merge_1)
# tail(merge_data)
head(merge_1)
head(data)

full_data <- merge_1 %>%
          left_join(data, by = c("date", "Province_State")) %>%
          select(-c(1,2))

full_data$spend_all_inclow <- as.numeric(full_data$spend_all_inclow)
full_data$emp_combined_inclow <- as.numeric(full_data$emp_combined_inclow)
full_data$emp_combined_incmiddle <- as.numeric(full_data$emp_combined_incmiddle)
full_data$emp_combined_ss40 <- as.numeric(full_data$emp_combined_ss40)
full_data$emp_combined_ss60 <- as.numeric(full_data$emp_combined_ss60)
full_data$emp_combined_ss65 <- as.numeric(full_data$emp_combined_ss65)
full_data$emp_combined_ss70 <- as.numeric(full_data$emp_combined_ss70)
full_data$merchants_ss60 <- as.numeric(full_data$merchants_ss60)
full_data$revenue_ss60 <- as.numeric(full_data$revenue_ss60)

write.csv(full_data,'/Users/mz/Desktop/Applied Data Science/ADS-group-3/output/full_data.csv')
# save(full_data, file="../output/data_use.RData")
```


```{r}
library(choroplethr)
library(choroplethrMaps)

# data('df_state_demographics')
# map_data <- df_state_demographics

full_data$region = tolower(full_data$Province_State)
full_data$value = full_data['spend_acf']
    

a <- full_data %>%
  filter(months(date) %in% month.name[1]) %>%
  group_by(region) %>%
  summarise(value = mean(spend_acf))


# function summary data frame
business_summary <- function(var, month) {
  df <- full_data %>%
          filter(months(date) %in% month.name[month]) %>%
          group_by(region) %>%
          summarise(value = mean(var))
  return(df)
}

# business_summary(spend_acf, 2)
# library(scales)
# label_percent()(a$value)

state_choropleth(df = a,
                 # title = colnames(full_data)[7], 
                 num_colors = 5)
```

































